server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:F:/intelliJ idea/confsvr/src/main/resources/config/licensingservice